name: Ping Secondary Website Twice Daily

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping_daily:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Secondary Website
        env:
          URL_SECONDARY: ${{ secrets.SECOND_WEBSITE_URL }}
        run: curl -X GET -I "$URL_SECONDARY" | head -n 1